# Generated by Django 5.2.8 on 2025-12-03 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='unity_price',
            new_name='unit_price',
        ),
    ]
